[package]
name = "eggScan"
version = "0.1.0"
authors = ["Andrew Eggleston <egglestonandrew927@gmail.com>"]

[dependencies]
lettre = "0.8"
lettre_email = "0.8"
notify = "4.0.0"

[replace]
"openssl:0.10.15" = { git = "https://github.com/sfackler/rust-openssl"}