[package]
name = "eggScan"
version = "0.1.0"
authors = ["Andrew Eggleston <egglestonandrew927@gmail.com>"]

[dependencies]
notify = "4.0.0"
reqwest = "0.9.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lettre_email = "0.8.2"
lettre = "0.8.2"
mime = "0.3.12"